# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: car.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tcar.proto\"?\n\x03\x43\x61r\x12\r\n\x05\x62rand\x18\x01 \x01(\t\x12\r\n\x05model\x18\x02 \x01(\t\x12\x1a\n\x12manufacturing_year\x18\x03 \x01(\x05\"\x1a\n\x04\x43\x61rs\x12\x12\n\x04\x63\x61rs\x18\x01 \x03(\x0b\x32\x04.Carb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'car_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CAR._serialized_start=13
  _CAR._serialized_end=76
  _CARS._serialized_start=78
  _CARS._serialized_end=104
# @@protoc_insertion_point(module_scope)
